receivers:
  opencensus:
    address: "127.0.0.1:55678"
processors:
  jaeger-1:
    num-workers: 5
    queue-size: 1000
    retry-on-failure: true
    sender-type: thrift-http
    thrift-http:
      collector-endpoint: http://jaeger-collector-target1:14268/api/traces
      headers: { "x-omnition-api-key":"F0000000-0000-0000-0000-000000000000" }
      timeout: 5s
  jaeger-2:
    num-workers: 5
    queue-size: 1000
    retry-on-failure: true
    sender-type: thrift-http
    thrift-http:
      collector-endpoint: http://jaeger-collector-target2:14268/api/traces
      headers: { "x-omnition-api-key":"F0000000-0000-0000-0000-000000000000" }
      timeout: 5s
sampling:
  mode: tail
  decision_wait: 10s
  num_traces: 20000
  policies:
    always-sample:
      exporter: jaeger-1
    attribute-filter: 
      exporter: jaeger-2
          